[env]
TERM = "xterm-256color"

[cursor.style]
blinking = "on"
shape = "Beam"
[window]
padding.x = 20
padding.y = 20
decorations = "full"
dynamic_title = true

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
size=13

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window.dimensions]
columns = 60
lines = 20

[colors.primary]
background = "0x000000"  # black base tint
